python src/train.py --task_name ag_news \
                    --labeled_per_class 2500 \
                    --train_batch_size 32 \
                    --test_batch_size 128 \
                    --eval_step 200 \
                    --lr 5e-5 \
                    --epochs 10 \
                    --architecture temporal \
                    --max_epochs 4 \
                    --last_epochs 2 \
                    --max_val 30 \
                    --aug
